In [1]:
import numpy as np
import pandas as pd

In [9]:

# Exercise 1: Create a numpy array from 1 to 10 and reshape it to a 2x5 matrix
arr1 = np.arange(1, 11).reshape(2, 5)
print(arr1, "\n")

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] 



In [10]:
# Exercise 2: Create a numpy array from 1 to 20 and extract elements between index 5 and 15
arr2 = np.arange(1, 21)
extracted_elements = arr2[5:16]
print(extracted_elements, "\n")

[ 6  7  8  9 10 11 12 13 14 15 16] 



In [11]:
# Exercise 3: Create a Pandas series and add a new item
fruits = pd.Series({'apples': 3, 'bananas': 2, 'oranges': 1})
fruits['pears']=4
print(fruits, "\n")

apples     3
bananas    2
oranges    1
pears      4
dtype: int64 



In [14]:
# Exercise 4: Create a DataFrame with name, age, gender
data = {
    'name': ['John', 'Emy', 'Robin', 'Joby', 'Philip', 'Susan', 'David', 'Alvina', 'Sachu', 'Dhoni'],
    'age': [25, 30, 28, 35, 40, 22, 29, 33, 26, 31],
    'gender': ['Male', 'Female', 'Male', 'Female', 'Male', 'Female', 'Male', 'Female', 'Male', 'Male']
}
df = pd.DataFrame(data)
print(df, "\n")

     name  age  gender
0    John   25    Male
1     Emy   30  Female
2   Robin   28    Male
3    Joby   35  Female
4  Philip   40    Male
5   Susan   22  Female
6   David   29    Male
7  Alvina   33  Female
8   Sachu   26    Male
9   Dhoni   31    Male 



In [15]:

# Exercise 5: Add a new column 'occupation' with predefined values
df['occupation'] = ['Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer']
print(df, "\n")

     name  age  gender  occupation
0    John   25    Male  Programmer
1     Emy   30  Female     Manager
2   Robin   28    Male     Analyst
3    Joby   35  Female  Programmer
4  Philip   40    Male     Manager
5   Susan   22  Female     Analyst
6   David   29    Male  Programmer
7  Alvina   33  Female     Manager
8   Sachu   26    Male     Analyst
9   Dhoni   31    Male  Programmer 



In [16]:

# Exercise 6: Select rows where age is greater than or equal to 30
filtered_df = df[df['age'] >= 30]
print(filtered_df, "\n")

     name  age  gender  occupation
1     Emy   30  Female     Manager
3    Joby   35  Female  Programmer
4  Philip   40    Male     Manager
7  Alvina   33  Female     Manager
9   Dhoni   31    Male  Programmer 



In [17]:
# Exercise 7: Convert DataFrame to CSV, read it back, and display contents
df.to_csv("data.csv", index=False)
df_read = pd.read_csv("data.csv")
print(df_read, "\n")

     name  age  gender  occupation
0    John   25    Male  Programmer
1     Emy   30  Female     Manager
2   Robin   28    Male     Analyst
3    Joby   35  Female  Programmer
4  Philip   40    Male     Manager
5   Susan   22  Female     Analyst
6   David   29    Male  Programmer
7  Alvina   33  Female     Manager
8   Sachu   26    Male     Analyst
9   Dhoni   31    Male  Programmer 

